### ISSUE TITLE
Ubuntu16 image build failing

### ISSUE THREAD

**Issue by Echsecutor** [hyperledger/indy-node-container#100]
Seems like the deb package in the sov repo (or the dependency resolution) has changed:

https://github.com/hyperledger/indy-node-container/runs/7873212017?check_suite_focus=true

**Comment by Echsecutor** [comment]
```
 indy-node : Depends: indy-plenum (= 1.12.4) but 1.12.5 is to be installed
```

sounds like apt could have figured out the fix herself... :wink:

**Comment by WadeBarnes** [comment]
There was a new release of node and plenum last week, `1.12.5`.  As you have discovered `apt` is not smart (this is a common problem), it will try to install the latest version of whatever packages it finds (regardless of the package dependencies), which is annoying to say the least as it ends up causing these sorts of issues.  I'm currently working on another release `1.12.6`, which fixes an issue discovered on older nodes with the automated pool-upgrade process.
