### ISSUE TITLE
podman dependency in node controller

### ISSUE THREAD

**Issue by Echsecutor** [hyperledger/indy-node-container#112]
In https://github.com/hyperledger/indy-node-container/pull/107 I removed podman from the controller
- as a quick fix (apt install was failing and so did the lvl1 solution)
- why do we install podman into the container in the first place?

If we need podman, we need to solve the packacke dependency issues. TBD [in our next call](https://wiki.hyperledger.org/display/indy/Indy+Container+Shipping+Company).

@tsurai @mgmgwi

**Comment by Echsecutor** [comment]
Yes we do want to have podman, but actually only the CLI

- find a package (possibly on different base image) that does not depend on saystemd and install that one
  - Simplest solution: fix old version

**Comment by tsurai** [comment]
The original problem seems to have been resolved upstream and the package can be installed again. I've been unable to find a way to only install an remote API client and avoid the unneeded requirements.

**Comment by Echsecutor** [comment]
@tsurai  from https://podman.io/getting-started/installation#installing-on-linux
> CAUTION: The Kubic repo is NOT recommended for production use. 

-> do we need those? or can we use the version from the ubuntu repos? Maybe for some later ubuntu version?

**Comment by Echsecutor** [comment]
Ok, I have tried quite a few base containers and eithere there is no python 3.5 or no podman available... lets stick with your ubuntu18 + kubic debs for now. ;)

**Comment by Echsecutor** [comment]
decision as of 2022-10-14:

- Build an additional controller image without podman + "non prod" sources

**Comment by Echsecutor** [comment]
RIP
