### ISSUE TITLE
Remove plenum and node specific dependencies.

### ISSUE THREAD

**Issue by pSchlarb** [hyperledger/indy-node-container#126]
Since node and plenum fixed the dependencies settings described in 
https://github.com/hyperledger/indy-node/issues/1799 
and fixed in 
https://github.com/hyperledger/indy-plenum/pull/1635

The specific dependencies (eg. ursa, rocksdb) should be removed  in the Dockerfiles to not cause issues when they are updated in node/plenum.

**Comment by Echsecutor** [comment]
Please just remove the dependencies from the docker file. If the build goes through, I am more than happy to accept the PR! :wink:

**Comment by pSchlarb** [comment]
Since it is fixed in #127, i will close this issue.
