### ISSUE TITLE
History re-write: commit sign off

### ISSUE THREAD

**Issue by Echsecutor** [hyperledger/indy-node-container#75]
Rewrite history and add correct sign off message to all commit messages

```
Signed-off-by: Author Name <authoremail@example.com>
```

- https://stackoverflow.com/questions/3690049/rewriting-git-history-how-do-i-remove-a-sign-off
- https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by mgmgwi** [comment]
Via https://github.com/newren/git-filter-repo

```
git-filter-repo --message-callback '
  if b"Signed-off-by:" not in message:
    message += b"\nSigned-off-by: Me My <self@and.eye>"
  return re.sub(b"[Ee]-?[Mm][Aa][Ii][Ll]", b"email", message)'
```

https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#CALLBACKS

**Comment by Echsecutor** [comment]
it has been done. :wink:
