### ISSUE TITLE
docker-compose.yaml is invalid

### ISSUE THREAD

**Issue by wollooo** [hyperledger/indy-node-container#76]
When I try to run the test network with docker I get the following error while executing step 3 in this tutorial:
https://github.com/IDunion/indy-node-container/tree/main/test#readme

`ERROR: The Compose file './docker-compose.yaml' is invalid because:
networks.idunion_local.ipam.config value Additional properties are not allowed ('gateway' was unexpected)`

I use Ubuntu 20.04 LTS with the following docker and docker compose:

	Client: Docker Engine - Community
     Version:           20.10.12
     API version:       1.41
     Go version:        go1.16.12
     Git commit:        e91ed57
     Built:             Mon Dec 13 11:45:33 2021
     OS/Arch:           linux/amd64
     Context:           default
     Experimental:      true
    
    Server: Docker Engine - Community
     Engine:
      Version:          20.10.12
      API version:      1.41 (minimum version 1.12)
      Go version:       go1.16.12
      Git commit:       459d0df
      Built:            Mon Dec 13 11:43:42 2021
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          1.4.12
      GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
     runc:
      Version:          1.0.2
      GitCommit:        v1.0.2-0-g52b36a2
     docker-init:
      Version:          0.19.0
      GitCommit:        de40ad0

    docker-compose version 1.25.5, build 8a1c60f6
    docker-py version: 4.1.0
    CPython version: 3.7.5
    OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by udosson** [comment]
From the docs (https://docs.docker.com/compose/compose-file/compose-file-v3/#ipam)
"Additional IPAM configurations, such as gateway, are only honored for version 2 at the moment."

We use `gateway` at https://github.com/IDunion/indy-node-container/blob/main/test/docker-compose.yaml#L202

@wollooo could you please add the output of `docker-compose version` to your issue?

**Comment by wollooo** [comment]
Problem solved.
Upgarded docker-compose to version 1.29.2 and it works!

**Comment by udosson** [comment]
Could you create PR that adds the docker-compose version as a requirement to the Readme file of the ./test folder? Then we can close this issue

**Comment by Echsecutor** [comment]
@wollooo many thanks for pointing that white spot in the documention out. I have written a couple of words in that direction, please check/add to https://github.com/IDunion/indy-node-container/tree/documenting_dependencies and open a PR! :)

**Comment by wollooo** [comment]
@udosson @Echsecutor I have added a few lines to the readme. It is now more a step by step guide to make things easier in the future. Please check https://github.com/IDunion/indy-node-container/pull/77

**Comment by Echsecutor** [comment]
Many thanks for providing the imrpoved documentation!
