### ISSUE TITLE
Ensure Tag Convention for Upgrades for Indy Node in Networks via node-controller

### ISSUE THREAD

**Issue by solidnerd** [hyperledger/indy-node-container#89]
We want to think about a workflow of how upgrades can work.

1. Announce of Upgrade in the network
2. Announcement of changed apt packages 

Latest images needs to available before update
Different Tags for usage and what does it mean when to use
latest → Development
prod → For Production Upgrades
* indy-node:prod-bullseye-20221012
* indy-node:prod-ubuntu

Use

**Comment by Echsecutor** [comment]
Obsolet. We changed tagging in https://github.com/hyperledger/indy-node-container/pull/121 and for the latest controller discussion see https://wiki.hyperledger.org/pages/viewpage.action?pageId=78022087
