### ISSUE TITLE
Store secret for slack push notifications 

### ISSUE THREAD

**Issue by Echsecutor** [hyperledger/indy-node-container#93]
@swcurran could you add the Secret:
name: SLACK_WEBHOOK_URL_IDU

To this repo? Or should I talk to someone else?

Background : @zickau has implemented push notifications for our container security scans and this secret is needed in order to push to our id union slack channel.

Many thanks!

**Comment by swcurran** [comment]
@ryjones -- could you please take care of this?  Thanks!

**Comment by ryjones** [comment]
Hi, @swcurran @Echsecutor - please talk to me on Discord
